-- Repair org tables corrupted by a partial drizzle-kit rename/type change.
-- Recreate with camelCase columns matching src/server/db/schema.ts.

DROP TABLE IF EXISTS "pg-drizzle_tender_approval_step" CASCADE;
DROP TABLE IF EXISTS "pg-drizzle_group_member" CASCADE;
DROP TABLE IF EXISTS "pg-drizzle_organization_member" CASCADE;
DROP TABLE IF EXISTS "pg-drizzle_organization_group" CASCADE;

-- Keep organization + domain if healthy; recreate group/member/approval tables.

CREATE TABLE "pg-drizzle_organization_group" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "organizationId" integer NOT NULL REFERENCES "pg-drizzle_organization"(id) ON DELETE CASCADE,
  name varchar(256) NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS organization_group_org_idx ON "pg-drizzle_organization_group" ("organizationId");

CREATE TABLE "pg-drizzle_organization_member" (
  "organizationId" integer NOT NULL REFERENCES "pg-drizzle_organization"(id) ON DELETE CASCADE,
  "userId" varchar(255) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  "orgRole" varchar(32) NOT NULL DEFAULT 'member',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("organizationId", "userId")
);
CREATE INDEX IF NOT EXISTS organization_member_user_idx ON "pg-drizzle_organization_member" ("userId");

CREATE TABLE "pg-drizzle_group_member" (
  "groupId" integer NOT NULL REFERENCES "pg-drizzle_organization_group"(id) ON DELETE CASCADE,
  "userId" varchar(255) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("groupId", "userId")
);
CREATE INDEX IF NOT EXISTS group_member_user_idx ON "pg-drizzle_group_member" ("userId");

CREATE TABLE "pg-drizzle_tender_approval_step" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "tenderId" integer NOT NULL REFERENCES "pg-drizzle_tender"(id) ON DELETE CASCADE,
  "groupId" integer NOT NULL REFERENCES "pg-drizzle_organization_group"(id),
  step_order integer NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  "actedById" varchar(255) REFERENCES "user"(id),
  "actedAt" timestamptz,
  note text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tender_approval_step_order_unique UNIQUE ("tenderId", step_order)
);
CREATE INDEX IF NOT EXISTS tender_approval_step_tender_idx ON "pg-drizzle_tender_approval_step" ("tenderId");
CREATE INDEX IF NOT EXISTS tender_approval_step_group_idx ON "pg-drizzle_tender_approval_step" ("groupId");

-- Drop leftover snake_case columns on organization/domain if any remain.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'pg-drizzle_organization' AND column_name = 'created_at'
  ) THEN
    ALTER TABLE "pg-drizzle_organization" DROP COLUMN IF EXISTS created_at;
    ALTER TABLE "pg-drizzle_organization" DROP COLUMN IF EXISTS updated_at;
    ALTER TABLE "pg-drizzle_organization" DROP COLUMN IF EXISTS type;
  END IF;
END $$;
