ALTER TABLE "user" ADD COLUMN IF NOT EXISTS is_platform_admin boolean NOT NULL DEFAULT false;
ALTER TABLE "user" DROP COLUMN IF EXISTS role;

CREATE TABLE IF NOT EXISTS "pg-drizzle_organization" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(256) NOT NULL,
  type varchar(32) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);
CREATE INDEX IF NOT EXISTS organization_type_idx ON "pg-drizzle_organization" (type);

CREATE TABLE IF NOT EXISTS "pg-drizzle_organization_domain" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  organization_id integer NOT NULL REFERENCES "pg-drizzle_organization"(id) ON DELETE CASCADE,
  domain varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT organization_domain_unique UNIQUE (domain)
);
CREATE INDEX IF NOT EXISTS organization_domain_org_idx ON "pg-drizzle_organization_domain" (organization_id);

CREATE TABLE IF NOT EXISTS "pg-drizzle_organization_member" (
  organization_id integer NOT NULL REFERENCES "pg-drizzle_organization"(id) ON DELETE CASCADE,
  user_id varchar(255) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  org_role varchar(32) NOT NULL DEFAULT 'member',
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, user_id)
);
CREATE INDEX IF NOT EXISTS organization_member_user_idx ON "pg-drizzle_organization_member" (user_id);

CREATE TABLE IF NOT EXISTS "pg-drizzle_organization_group" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  organization_id integer NOT NULL REFERENCES "pg-drizzle_organization"(id) ON DELETE CASCADE,
  name varchar(256) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);
CREATE INDEX IF NOT EXISTS organization_group_org_idx ON "pg-drizzle_organization_group" (organization_id);

CREATE TABLE IF NOT EXISTS "pg-drizzle_group_member" (
  group_id integer NOT NULL REFERENCES "pg-drizzle_organization_group"(id) ON DELETE CASCADE,
  user_id varchar(255) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id)
);
CREATE INDEX IF NOT EXISTS group_member_user_idx ON "pg-drizzle_group_member" (user_id);

INSERT INTO "pg-drizzle_organization" (name, type)
SELECT 'Legacy Buyer', 'buyer'
WHERE NOT EXISTS (SELECT 1 FROM "pg-drizzle_organization" LIMIT 1);

ALTER TABLE "pg-drizzle_tender" ADD COLUMN IF NOT EXISTS organization_id integer;
UPDATE "pg-drizzle_tender" SET organization_id = (SELECT id FROM "pg-drizzle_organization" ORDER BY id LIMIT 1) WHERE organization_id IS NULL;
ALTER TABLE "pg-drizzle_tender" ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE "pg-drizzle_tender" DROP CONSTRAINT IF EXISTS "pg-drizzle_tender_organization_id_pg-drizzle_organization_id_fk";
ALTER TABLE "pg-drizzle_tender"
  ADD CONSTRAINT "pg-drizzle_tender_organization_id_pg-drizzle_organization_id_fk"
  FOREIGN KEY (organization_id) REFERENCES "pg-drizzle_organization"(id);

CREATE INDEX IF NOT EXISTS tender_organization_idx ON "pg-drizzle_tender" (organization_id);

CREATE TABLE IF NOT EXISTS "pg-drizzle_tender_approval_step" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tender_id integer NOT NULL REFERENCES "pg-drizzle_tender"(id) ON DELETE CASCADE,
  group_id integer NOT NULL REFERENCES "pg-drizzle_organization_group"(id),
  step_order integer NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  acted_by_id varchar(255) REFERENCES "user"(id),
  acted_at timestamptz,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tender_approval_step_order_unique UNIQUE (tender_id, step_order)
);
CREATE INDEX IF NOT EXISTS tender_approval_step_tender_idx ON "pg-drizzle_tender_approval_step" (tender_id);
CREATE INDEX IF NOT EXISTS tender_approval_step_group_idx ON "pg-drizzle_tender_approval_step" (group_id);
